// ⚠️ AUTOGENERATED: do not edit by hand
export const FONT_FILES = {
  Bad_Script: {
    400: require("@assets/fonts/Bad_Script/BadScript.ttf"),
  },
  Comfortaa: {
    300: require("@assets/fonts/Comfortaa/Comfortaa-300.ttf"),
    400: require("@assets/fonts/Comfortaa/Comfortaa-400.ttf"),
    500: require("@assets/fonts/Comfortaa/Comfortaa-500.ttf"),
    600: require("@assets/fonts/Comfortaa/Comfortaa-600.ttf"),
    700: require("@assets/fonts/Comfortaa/Comfortaa-700.ttf"),
  },
  Lora: {
    400: require("@assets/fonts/Lora/Lora-400.ttf"),
    500: require("@assets/fonts/Lora/Lora-500.ttf"),
    600: require("@assets/fonts/Lora/Lora-600.ttf"),
    700: require("@assets/fonts/Lora/Lora-700.ttf"),
  },
  Montserrat: {
    300: require("@assets/fonts/Montserrat/Montserrat-300.ttf"),
    400: require("@assets/fonts/Montserrat/Montserrat-400.ttf"),
    500: require("@assets/fonts/Montserrat/Montserrat-500.ttf"),
    600: require("@assets/fonts/Montserrat/Montserrat-600.ttf"),
    700: require("@assets/fonts/Montserrat/Montserrat-700.ttf"),
  },
  Nata_Sans: {
    300: require("@assets/fonts/Nata_Sans/NataSans-300.ttf"),
    400: require("@assets/fonts/Nata_Sans/NataSans-400.ttf"),
    500: require("@assets/fonts/Nata_Sans/NataSans-500.ttf"),
    600: require("@assets/fonts/Nata_Sans/NataSans-600.ttf"),
    700: require("@assets/fonts/Nata_Sans/NataSans-700.ttf"),
  },
  PT_Sans: {
    400: require("@assets/fonts/PT_Sans/PTSans-400.ttf"),
    700: require("@assets/fonts/PT_Sans/PTSans-700.ttf"),
  },
  Raleway: {
    300: require("@assets/fonts/Raleway/Raleway-300.ttf"),
    400: require("@assets/fonts/Raleway/Raleway-400.ttf"),
    500: require("@assets/fonts/Raleway/Raleway-500.ttf"),
    600: require("@assets/fonts/Raleway/Raleway-600.ttf"),
    700: require("@assets/fonts/Raleway/Raleway-700.ttf"),
  },
  Roboto_Condensed: {
    300: require("@assets/fonts/Roboto_Condensed/RobotoCondensed-300.ttf"),
    400: require("@assets/fonts/Roboto_Condensed/RobotoCondensed-400.ttf"),
    500: require("@assets/fonts/Roboto_Condensed/RobotoCondensed-500.ttf"),
    600: require("@assets/fonts/Roboto_Condensed/RobotoCondensed-600.ttf"),
    700: require("@assets/fonts/Roboto_Condensed/RobotoCondensed-700.ttf"),
  },
  Roboto_Slab: {
    300: require("@assets/fonts/Roboto_Slab/RobotoSlab-300.ttf"),
    400: require("@assets/fonts/Roboto_Slab/RobotoSlab-400.ttf"),
    500: require("@assets/fonts/Roboto_Slab/RobotoSlab-500.ttf"),
    600: require("@assets/fonts/Roboto_Slab/RobotoSlab-600.ttf"),
    700: require("@assets/fonts/Roboto_Slab/RobotoSlab-700.ttf"),
  },
} as const;
